---
baseURL: "https://blog.amritanshu.in/"
languageCode: "en-us"
title: "Amritanshu Pandey"
theme: "hugo-kiera"
pygmentsCodeFences: true
summaryLength: 30
enableEmoji: true
disqusShortname: amritanshu-in

author:
    name: "Amritanshu Pandey"           #Author name
    github: "amritanshu-pandey"         #Github username
    linkedin: "amritanshupandey"       #LinkedIn username
    twitter: "iamritanshu"        #Twitter username
    stackoverflow: "users/2329689/amritanshu-pandey"  #StackOverflow username

params:
    tagline: "Linux, Python, OSS, Devops"
    customCSS: []  #Optional Customised CSS
    favicon: "https://avatars3.githubusercontent.com/u/5570314"
