---
baseURL: "https://blog.amritanshu.in/"
languageCode: "en-us"
title: "Amritanshu Pandey"
theme: "ghostwriter"
enableEmoji: true

author:
    name: "Amritanshu Pandey"           #Author name
    github: "amritanshu-pandey"         #Github username
    linkedin: "amritanshupandey"       #LinkedIn username
    twitter: "iamritanshu"        #Twitter username
    stackoverflow: "users/2329689/amritanshu-pandey"  #StackOverflow username

copyright: Amritanshu Pandey
googleAnalytics: amritanshu.in
disqusShortname: amritanshu-in
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

taxonomies:
  tag: tags

params:
  tagline: "Linux, Python, OSS, Devops"
  customCSS: []  #Optional Customised CSS
  favicon: "https://avatars3.githubusercontent.com/u/5570314"
#   mainSections:
#     - post
  intro: true
  headline: Linux, Python, OSS, Devops
  description: ""
  github: "https://github.com/amritanshu-pandey"
  gitlab: "https://gitlab.com/amritanshu-pandey"
  twitter: "https://twitter.com/iAMRITANSHU"
  stackoverflow: "https://stackoverflow.com/users/2329689/amritanshu-pandey"
  email: email@amritanshu.in
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    # - name: Projects
    #   url: /project/
    #   weight: 2
    # - name: Contact
    #   url: /page/contact/
    #   weight: 3
    # - name: About
    #   url: /page/about/
    #   weight: 4